bcamlppx: removed match to Invalid_argument exception.

diff --git a/tools/mkproto b/tools/mkproto
--- a/tools/mkproto
+++ b/tools/mkproto
@@ -11,23 +11,73 @@
 #  it under the terms of the GNU  General Public License (GPL) ver. 2, as
 #  specified in the LICENSE-en file in the project root folder.
 #  ——————————————————————————————————————————————————————————————————————
-[ -z "$1" ] || [ -z "$2" ] || [ -n "$3" ] && {
-cat <<END
-Usage: mkproto TAG FILE
 
-Read the given FILE (in ACME cross assembler format) and print on standard
-output a list of dummy C prototypes for all primitives it contains.
+function usage {
+    cat <<EOF 
+Usage: $0 -p|--prefix  TAG FILE
+       $0 -c|--comment TAG FILE
+Generate dummy C prototypes for all primitives in FILE matching TAG.
+Example: $0 -p my_prim_ primitives.asm
 
-The output can be redirected to a .c file suitable to link the user-defined
-primitives with object code files generated by the BreadCaml compiler.
+Read the provided ACME assembly FILE and print to standard output a list of
+dummy C  prototypes for all the  primitives it contains. The  output can be
+redirected to a C file suitable  for linking the user-defined primitives in
+FILE with the object code files generated by the BreadCaml compilers.
 
-The entrypoint line of each primitive must start with a global label followed by
-a ";TAG" comment, with no characters but spaces o tabs between them. Spaces and
-tabs are admitted between ';' and TAG too, as more than a single semicolon.
+TAG  is a  user-defined sequence  of characters  that complies  with ACME's
+lexical rules for  global symbols (it begins  with a letter or  ‘_’ and may
+contain letters, digits, or ‘_’).
 
-mkproto is part of The BreadCaml Project.
-END
-exit 0
+With the ‘-p’ or ‘--prefix’ option, any  global label at the beginning of a
+line in  FILE that starts  with TAG and is  not followed by  any characters
+other than spaces or tabs is identified as the name of a primitive.
+
+With the ‘c’ or ‘--comment’ option, any  global label at the beginning of a
+line  in FILE  followed by  one or  more ‘;’  and by  ‘TAG’, with  no other
+characters on the line except spaces  and tabs as separators, is identified
+as the name of a primitive.
+
+$0 is part of The BreadCaml Project.
+EOF
 }
 
-sed -nE "s:^[ \t]*([_A-Za-z][_A-Za-z0-9]*)[ \t;]+$1[ \t]*$:void \1(){}:p" "$2"
+function check_tag { # $1: TAG
+    [[ $1 =~ ^([_A-Za-z]+[0-9]*)+$ ]] || {
+	echo "Illegal tag: ‘$1’." 1>&2
+	exit 1
+    }
+}
+
+function check_file { # $1: FILE
+    [[ -r $1 ]] || {
+	echo "File does not exist or is unreadable: ‘$1’." 1>&2
+	exit 1
+    }
+}
+
+function syntax_error {
+    echo -e "$0: Syntax error.\nTry ‘$0 --help’ for more information." 1>&2
+    exit 1
+}
+
+case "$#:$1" in
+    1:--help)
+	usage
+	;;
+    3:-p|3:--prefix)
+	check_tag "$2"
+	check_file "$3"
+	sed -nE \
+	    "s/^($2[_A-Za-z0-9]+)[ \t]*$/void \1() {}/p" \
+	    "$3"
+	;;
+    3:-c|3:--comment)
+	check_tag "$2"
+	check_file "$3"
+	sed -nE \
+	    "s/^(([_A-Za-z]+[0-9]*)+)([ \t]*;)+[ \t]*$2[ \t]*$/void \1() {}/p" \
+	    "$3"
+	;;
+    *)
+	syntax_error
+esac
