Namespace: all global labels now begin with "caml_", but opcode macros ("iHH") and those defined in 'loader.asm'.

diff --git a/tools/mkproto b/tools/mkproto
--- a/tools/mkproto
+++ b/tools/mkproto
@@ -1,62 +1,57 @@
 #!/bin/bash
-#  ——————————————————————————————————————————————————————————————————————
-#  Progetto BreadCaml / The BreadCaml Project
-#  Copyright (C) 21-Apr-2026 Piero Furiesi
-#  
-#  Questo  programma  è software  libero;  può  essere ridistribuito  e/o
-#  modificato nei termini della licenza GNU GPL ver. 2,  come specificato
-#  nel file LICENZA-it nella cartella principale del progetto.
-#  
-#  This program is  free software; you can redistribute  it and/or modify
-#  it under the terms of the GNU  General Public License (GPL) ver. 2, as
-#  specified in the LICENSE-en file in the project root folder.
-#  ——————————————————————————————————————————————————————————————————————
 
 function usage {
-    cat <<EOF 
+    cat <<EOF
 Usage: $0 -p|--prefix  TAG FILE
        $0 -c|--comment TAG FILE
 Generate dummy C prototypes for all primitives in FILE matching TAG.
 Example: $0 -p my_prim_ primitives.asm
 
-Read the provided ACME assembly FILE and print to standard output a list of
-dummy C  prototypes for all the  primitives it contains. The  output can be
-redirected to a C file suitable  for linking the user-defined primitives in
-FILE with the object code files generated by the BreadCaml compilers.
+Read the ACME assembly FILE and print  to standard output a list of dummy C
+prototypes for all the primitives it contains. The output can be redirected
+to a C file suitable for linking  the primitives with the object code files
+generated by the BreadCaml compilers.
 
 TAG  is a  user-defined sequence  of characters  that complies  with ACME's
 lexical rules for  global symbols (it begins  with a letter or  ‘_’ and may
 contain letters, digits, or ‘_’).
 
-With the ‘-p’ or ‘--prefix’ option, any  global label at the beginning of a
-line in  FILE that starts  with TAG and is  not followed by  any characters
-other than spaces or tabs is identified as the name of a primitive.
+A global label at the beginning of a line in FILE is identified as the name
+of a primitive, and its C prototype is generated, if:
 
-With the ‘c’ or ‘--comment’ option, any  global label at the beginning of a
-line  in FILE  followed by  one or  more ‘;’  and by  ‘TAG’, with  no other
-characters on the line except spaces  and tabs as separators, is identified
-as the name of a primitive.
+- the ‘-p’ or ‘--prefix’ option is  specified, the label starts with ‘TAG’,
+  and it is not followed by any characters other than spaces or tabs;
+or
+- the ‘-c’ or ‘--comment’ option is specified, the label is followed by the
+  comment  ‘TAG’ introduced  by one  or more  ‘;’, and  there are  no other
+  characters on the line except spaces and tabs as separators.
 
 $0 is part of The BreadCaml Project.
 EOF
 }
 
+LABEL1ST='[_A-Za-z]'
+LABELNXT='[_A-Za-z0-9]*'
+LABEL="$LABEL1ST$LABELNXT"
+SEP='[ \t]*'
+PROTO='void \1 () {}'
+
 function check_tag { # $1: TAG
-    [[ $1 =~ ^([_A-Za-z]+[0-9]*)+$ ]] || {
-	echo "Illegal tag: ‘$1’." 1>&2
+    [[ $1 =~ ^$LABEL$ ]] || {
+	echo "$0: illegal tag ‘$1’." 1>&2
 	exit 1
     }
 }
 
 function check_file { # $1: FILE
     [[ -r $1 ]] || {
-	echo "File does not exist or is unreadable: ‘$1’." 1>&2
+	echo "$0: file ‘$1’ does not exist or is unreadable." 1>&2
 	exit 1
     }
 }
 
 function syntax_error {
-    echo -e "$0: Syntax error.\nTry ‘$0 --help’ for more information." 1>&2
+    echo -e "$0: syntax error.\nTry ‘$0 --help’ for more information." 1>&2
     exit 1
 }
 
@@ -67,16 +62,12 @@ case "$#:$1" in
     3:-p|3:--prefix)
 	check_tag "$2"
 	check_file "$3"
-	sed -nE \
-	    "s/^($2[_A-Za-z0-9]+)[ \t]*$/void \1() {}/p" \
-	    "$3"
+	sed -nE "s/^($2$LABELNXT)$SEP$/$PROTO/p" "$3"
 	;;
     3:-c|3:--comment)
 	check_tag "$2"
 	check_file "$3"
-	sed -nE \
-	    "s/^(([_A-Za-z]+[0-9]*)+)([ \t]*;)+[ \t]*$2[ \t]*$/void \1() {}/p" \
-	    "$3"
+	sed -nE "s/^($LABEL)$SEP;+$SEP$2$SEP$/$PROTO/p" "$3"
 	;;
     *)
 	syntax_error
